Repository spidernet-io/e2eframework, pull requests merged in 2022-10, with the labels that each got.

#94 Adding switches to CIDRManager
  framework/framework.go
Labels: issue/feature, pr/release/none-required, pr/ready-review

#93 add api createService
  framework/service.go
  framework/service_test.go
Labels: pr/release/none-required

#104 add endpoint api
  framework/endpoint.go
  framework/endpoint_test.go
Labels: pr/release/feature-new

#105 add docker command
  .github/workflows/lint-golang.yaml
  Makefile
  framework/command.go
  framework/command_test.go
  framework/kind.go
  framework/kind_test.go
Labels: pr/release/feature-new
