Repository spidernet-io/e2eframework, pull requests merged in 2022-08, with the labels that each got.

#71 E2E: add CreateNamespaceUntilDefaultServiceAccountReady api
  framework/namespace.go
  framework/namespace_test.go
  framework/serviceaccounts.go
  framework/serviceaccounts_test.go
Labels: pr/release/none-required

#75 E2E: fix log and add api WaitAllPodUntilRunning
  framework/events.go
  framework/framework.go
  framework/pod.go
  framework/pod_test.go
Labels: pr/release/none-required, pr/ready-review

#76 E2E: add api CreateDaemonsetUntilReady for spiderpool
  framework/daemonset.go
  framework/daemonset_test.go
Labels: pr/release/none-required, pr/ready-review

#78 fix delete until pod ready
  framework/pod.go
Labels: pr/release/bug, pr/ready-review

#79 E2E: add api ExecKubectl
  framework/kind.go
  framework/kind_test.go
Labels: pr/release/none-required

#80 E2E: add api ExecCommondInPod
  framework/kind.go
  framework/pod_test.go
Labels: pr/release/none-required
